_target_: builtins.dict
_convert_: all
_args_:
  - optimizer:
      _target_: torch.optim.Adam
      _partial_: true
      lr: 1e-3
    lr_scheduler:
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        _partial_: true
        factor: 0.5
        patience: 3
      monitor: val_loss
