DEFAULT_LOGGING__LEVEL = 'INFO'
DEFAULT_LOGGING__FORMAT = '[%(asctime)s] - %(name)s - [%(levelname)s] - %(message)s'
DEFAULT_LOGGING__DATEFMT = '%Y-%m-%d %H:%M:%S'
DEFAULT_LOGGING__FILEMODE = 'a'
DEFAULT_LOGGING__ENCODING = 'utf-8'

DEFAULT_SPLIT_RATIO = 0.8
DEFAULT_DEVICE = 'cuda'
DEFAULT_BATCH_SIZE = 64
